apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: hadoop
  labels:
    app: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: hadoop                                  # 6
    spec:
      containers:
        - image: sequenceiq/hadoop-docker
          imagePullPolicy: Always                         # 7
          name: hadoop
          ports:
            - containerPort: 80