apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sonar                                  # 6
    spec:
      containers:
        - image: joebaird/sonarscanner
          imagePullPolicy: Always                         # 7
          name: sonarscanner
          ports:
            - containerPort: 80
        - image: sonarqube
          imagePullPolicy: Always                         # 7
          name: sonarqube
          ports:
            - containerPort: 80
      